// Tedarikçinin kendi resmi marka sunumundan (50 marka) alınan tam liste —
// Tedarikçiler sayfasındaki aranabilir dizin ve ana sayfadaki logo şeritleri
// aynı kaynağı paylaşır. Alfabetik. Logo dosyaları: /images/brands/{slug}.png
// website: markanın resmi sitesi (mümkün olduğunda aftermarket/yedek parça
// bölümü) — WebSearch ile tek tek doğrulanmış gerçek URL'ler.
export const ALL_BRANDS: { slug: string; name: string; website?: string }[] = [
  { slug: "ajusa", name: "Ajusa", website: "https://ajusa.online/en/" },
  { slug: "akzonobel", name: "AkzoNobel", website: "https://www.akzonobel.com/" },
  { slug: "bilsteingroup", name: "Bilstein Group", website: "https://bilsteingroup.com/en/" },
  { slug: "borgwarner", name: "BorgWarner", website: "https://www.borgwarner.com/aftermarket" },
  { slug: "bosch", name: "Bosch", website: "https://www.boschaftermarket.com/" },
  { slug: "brembo", name: "Brembo", website: "https://www.brembo.com/en" },
  { slug: "clarios", name: "Clarios", website: "https://www.clarios.com/" },
  { slug: "cojali", name: "Cojali", website: "https://www.cojaliparts.com/en/" },
  { slug: "continental", name: "Continental", website: "https://www.continental-aftermarket.com/" },
  { slug: "corteco", name: "Corteco", website: "https://www.corteco.com/" },
  { slug: "denso", name: "Denso", website: "https://www.denso-am.eu/" },
  { slug: "dinex", name: "Dinex", website: "https://www.dinex.eu/" },
  { slug: "dolz", name: "Dolz", website: "https://www.idolz.com/en/" },
  { slug: "driv", name: "DRiV", website: "https://www.drivparts.com/" },
  { slug: "elring", name: "Elring", website: "https://www.elring.us/" },
  { slug: "forvia", name: "Forvia (Hella)", website: "https://www.hella.com/en/" },
  { slug: "gates", name: "Gates", website: "https://www.gates.com/" },
  { slug: "gkn", name: "GKN", website: "https://www.gknautomotive.com/en/aftermarket/" },
  { slug: "haynespro", name: "HaynesPro", website: "https://www.haynespro.com/" },
  { slug: "hengst", name: "Hengst Filtration", website: "https://www.hengst.com/en/solutions/industries/136-automotive-aftermarket" },
  { slug: "herthbuss", name: "Herth+Buss", website: "https://herthundbuss.com/en/" },
  { slug: "hlmando", name: "HL Mando", website: "https://hlmandoaftermarket.com/" },
  { slug: "kyb", name: "KYB", website: "https://kyb-europe.com/" },
  { slug: "liquimoly", name: "Liqui Moly", website: "https://www.liqui-moly.com/" },
  { slug: "mahle", name: "Mahle", website: "https://www.mahle-aftermarket.com/eu/en/" },
  { slug: "mannhummel", name: "Mann+Hummel", website: "https://www.mann-filter.com/" },
  { slug: "marelli", name: "Marelli", website: "https://www.magnetimarelli-parts-and-services.com/" },
  { slug: "meritor", name: "Meritor", website: "https://www.meritorpartsxpress.com/" },
  { slug: "monroe", name: "Monroe", website: "https://www.monroe.com/" },
  { slug: "nissens", name: "Nissens", website: "https://nissens.com/" },
  { slug: "niterra", name: "Niterra (NGK)", website: "https://www.ngkntk.com/" },
  { slug: "nrf", name: "NRF", website: "https://www.nrf.eu/" },
  { slug: "osram", name: "Osram", website: "https://www.osram.com/am/" },
  { slug: "philips", name: "Philips", website: "https://www.philips.com/" },
  { slug: "phinia", name: "Phinia (Delphi)", website: "https://www.delphiautoparts.com/" },
  { slug: "purflux", name: "Purflux Group", website: "https://purfluxgroup.com/" },
  { slug: "schaeffler", name: "Schaeffler", website: "https://www.schaeffler.com/en/divisions-products/automotive-aftermarket/" },
  { slug: "segautomotive", name: "SEG Automotive", website: "https://www.seg-automotive.com/" },
  { slug: "skf", name: "SKF", website: "https://vehicleaftermarket.skf.com/" },
  { slug: "stabilus", name: "Stabilus", website: "https://www.stabilus.com/" },
  { slug: "tecalliance", name: "TecAlliance", website: "https://www.tecalliance.net/" },
  { slug: "titanx", name: "TitanX", website: "https://www.titanx.com/" },
  { slug: "tmdfriction", name: "TMD Friction (Textar)", website: "https://tmdfriction.com/" },
  { slug: "totalenergies", name: "TotalEnergies", website: "https://lubricants.totalenergies.com/home" },
  { slug: "trucktec", name: "Trucktec Automotive", website: "https://www.trucktec.com/" },
  { slug: "ufifilters", name: "UFI Filters", website: "https://www.ufi-aftermarket.com/" },
  { slug: "valeo", name: "Valeo", website: "https://www.valeoservice.com/en-com" },
  { slug: "vitesco", name: "Vitesco Technologies", website: "https://www.vitesco-technologies.com/" },
  { slug: "wolflubricants", name: "Wolf Lubricants", website: "https://www.wolflubes.com/" },
  { slug: "zfaftermarket", name: "ZF Aftermarket", website: "https://aftermarket.zf.com/" },
];
