import type { LucideIcon } from "lucide-react";
import {
  Cog, Eye, Lightbulb, CircleDot, RotateCw, Navigation, Zap, Filter, Disc, Car, Waves, RefreshCw, Thermometer, CircleDashed, Wrench, Droplet, Settings2, PackageCheck, BatteryCharging, Snowflake, MoveVertical, Boxes, Fuel,
} from "lucide-react";

// Excel kaynağı "Kopya Delta Markalar -kategoriler.xlsx" (Sheet: Ürün Grupları,
// 30.159 satırlık ürün-marka verisinden agrege edilmiştir) — Tedarikçiler sayfasının
// kategori bölümünün TEK doğruluk kaynağı. brandSlugs, o kategoride ürün veren
// (Excel'de doğrulanmış) markaların gerçek listesidir — temsili/tahmini değildir.
// `name` alanı görüntülenen başlıktır; 4 kategoride (Motor, Elektrik, Araç
// Görünürlük-Uyarı Grubu, Süspansiyon-Taşıyıcı Sistem) aile başlığıyla anlam
// çakışması/belirsizlik yaratan orijinal Excel adı yerine daha net bir görüntü
// adı kullanılıyor — kapsam/marka listesi DEĞİŞMEDİ, yalnızca başlık netleşti.
// nameEn/descriptionEn: Content/UX Pass 01 — İngilizce sunum katmanı çevirisi.
// Kapsam/marka ilişkisini etkilemez, yalnızca `/en/*` sayfalarında görüntülenir.
export interface ProductCategory {
  name: string;
  nameEn: string;
  icon: LucideIcon;
  description: string;
  descriptionEn: string;
  brandSlugs: string[];
  /** Sunum katmanına özel öncelik sıralaması — YALNIZCA brandSlugs içindeki
   * markaların bir alt kümesi/yeniden sıralaması, yeni bir marka-kategori
   * ilişkisi eklemez. Not: Tedarikçiler kategori gezgininin marka alanı artık
   * alfabetik sırayla TÜM markaları tek seferde gösteriyor (expand/collapse
   * yok), bu yüzden featuredBrandSlugs o ekranda kullanılmıyor; alan ileride
   * başka bir öne-çıkarma ihtiyacı için veri olarak korunuyor. */
  featuredBrandSlugs?: string[];
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  { name: "Aks-Transmisyon", nameEn: "Axle & Transmission", icon: Cog, description: "Aks mili, diferansiyel ve güç aktarma organlarında OEM ve OEM eşdeğeri kapsam.", descriptionEn: "OEM and OEM-equivalent coverage for axle shafts, differentials and power transmission components.", brandSlugs: ["blueprint", "corteco", "fag", "febi", "gkn", "ina", "lemforder", "rapro", "skf", "spart", "swag", "ucel"], featuredBrandSlugs: ["skf", "gkn", "fag", "ina", "spart", "febi"] },
  { name: "Sinyalizasyon ve Görünürlük", nameEn: "Signaling & Visibility", icon: Eye, description: "Sinyal, uyarı ve görünürlük sistemlerinde araç güvenliğini tamamlayan ürün grubu.", descriptionEn: "Signal, warning and visibility components that complete vehicle safety systems.", brandSlugs: ["bosch", "cargo", "denso", "febi", "hella", "osram", "silbak", "swag", "valeo"], featuredBrandSlugs: ["bosch", "hella", "valeo", "osram", "silbak"] },
  { name: "Aydınlatma", nameEn: "Lighting", icon: Lightbulb, description: "Far, arka lamba ve iç aydınlatmada orijinal görünüm ve performans.", descriptionEn: "Original appearance and performance for headlamps, tail lamps and interior lighting.", brandSlugs: ["bosch", "hella", "valeo"], featuredBrandSlugs: ["hella", "bosch", "valeo"] },
  { name: "Conta-Keçe-O-Ring", nameEn: "Gaskets, Seals & O-Rings", icon: CircleDot, description: "Motor ve şanzıman sızdırmazlığında hassas ölçü ve malzeme uyumu.", descriptionEn: "Precise dimensional and material compatibility for engine and transmission sealing.", brandSlugs: ["blueprint", "bosch", "cargo", "corteco", "elring", "febi", "henkel", "liquimoly", "skf", "supsan", "swag", "ucel"], featuredBrandSlugs: ["elring", "corteco", "bosch", "febi", "supsan", "skf"] },
  { name: "Debriyaj-Volan", nameEn: "Clutch & Flywheel", icon: RotateCw, description: "Debriyaj seti, volan ve güç aktarma komponentlerinde eksiksiz kapsam.", descriptionEn: "Complete coverage of clutch kits, flywheels and power transmission components.", brandSlugs: ["blueprint", "borgwarner", "bosch", "corteco", "delphi", "febi", "ina", "luk", "rapro", "sachs", "skf", "trw", "valeo"], featuredBrandSlugs: ["luk", "sachs", "borgwarner", "valeo", "ina"] },
  { name: "Direksiyon", nameEn: "Steering", icon: Navigation, description: "Direksiyon kutusu, pompa ve rot sisteminde sürüş güvenliğine yönelik parçalar.", descriptionEn: "Steering gear, pump and tie rod components engineered for driving safety.", brandSlugs: ["delphi", "hlmando", "hattat", "kale", "lemforder", "rapro"], featuredBrandSlugs: ["lemforder", "delphi", "hattat", "kale"] },
  { name: "Elektrik Donanımı", nameEn: "Electrical Components", icon: Zap, description: "Araç elektroniği ve kablo donanımında geniş marka alternatifi.", descriptionEn: "A broad range of brand options for vehicle electronics and wiring components.", brandSlugs: ["behr", "beru", "blueprint", "bosch", "cargo", "champion", "delphi", "denso", "era", "febi", "hlmando", "hella", "ina", "mahle", "ngk", "nrf", "optima", "osram", "spart", "swag", "valeo"], featuredBrandSlugs: ["bosch", "denso", "valeo", "hella", "ngk", "beru", "optima", "spart"] },
  { name: "Filtre", nameEn: "Filters", icon: Filter, description: "Yağ, hava, yakıt ve kabin filtrelerinde periyodik bakım kapsamı.", descriptionEn: "Oil, air, fuel and cabin filters for scheduled maintenance.", brandSlugs: ["blueprint", "bosch", "corteco", "delphi", "denso", "febi", "filtron", "hlmando", "mahle", "mannfilter", "purflux", "spart", "swag", "valeo"], featuredBrandSlugs: ["mannfilter", "bosch", "mahle", "purflux", "filtron", "spart"] },
  { name: "Fren Sistemi", nameEn: "Brake System", icon: Disc, description: "Balata, disk ve hidrolik fren komponentlerinde OEM standardı.", descriptionEn: "OEM-standard brake pads, discs and hydraulic components.", brandSlugs: ["blueprint", "bosch", "brembo", "delphi", "febi", "ferodo", "frendi", "hlmando", "skf", "spart", "swag", "trw", "valeo"], featuredBrandSlugs: ["brembo", "trw", "ferodo", "bosch", "frendi", "spart"] },
  { name: "Kaporta-Karoseri", nameEn: "Body & Chassis Panels", icon: Car, description: "Kaporta ve karoseri parçalarında orijinal ölçü ve uyum garantisi.", descriptionEn: "Guaranteed original fit and dimensions for body and chassis panels.", brandSlugs: ["bosch", "febi", "spart", "ucel", "valeo"], featuredBrandSlugs: ["valeo", "bosch", "spart", "ucel", "febi"] },
  { name: "Kauçuk-Hortumlar-Borular", nameEn: "Rubber Hoses & Pipes", icon: Waves, description: "Motor ve yakıt sistemi hortum/boru hatlarında dayanıklı malzeme kalitesi.", descriptionEn: "Durable material quality for engine and fuel system hose and pipe lines.", brandSlugs: ["behr", "blueprint", "bosch", "corteco", "delphi", "fag", "febi", "gates", "gkn", "ina", "lemforder", "rapro", "skf", "spart", "swag", "trw", "ucel"], featuredBrandSlugs: ["gates", "corteco", "febi", "spart", "gkn"] },
  { name: "Kayış-Gergi-Rulman-Kit", nameEn: "Belt, Tensioner & Bearing Kits", icon: RefreshCw, description: "Triger/V kayışı, gergi ve rulman setlerinde tam kit çözümleri.", descriptionEn: "Complete kit solutions for timing/V-belts, tensioners and bearing sets.", brandSlugs: ["blueprint", "bosch", "cargo", "contitech", "corteco", "dayco", "dolz", "fag", "febi", "gates", "hlmando", "ina", "kale", "luk", "skf", "spart", "supsan", "swag", "taifun", "valeo"], featuredBrandSlugs: ["gates", "contitech", "dayco", "skf", "ina", "luk", "spart"] },
  { name: "Klima-Isıtma", nameEn: "Air Conditioning & Heating", icon: Thermometer, description: "Klima kompresörü, radyatör ve kabin konfor sistemlerinde tam kapsam.", descriptionEn: "Full coverage of AC compressors, radiators and cabin comfort systems.", brandSlugs: ["behr", "bosch", "delphi", "denso", "febi", "hlmando", "hella", "kale", "nrf", "spart", "swag", "valeo"], featuredBrandSlugs: ["behr", "denso", "valeo", "nrf", "bosch", "spart"] },
  { name: "Lastik-Jant", nameEn: "Tires & Wheels", icon: CircleDashed, description: "Lastik ve jant kategorisinde geniş ebat ve marka seçeneği.", descriptionEn: "A wide range of sizes and brands in the tire and wheel category.", brandSlugs: ["febi", "swag"], featuredBrandSlugs: ["febi", "swag"] },
  { name: "Motor İç Aksamı", nameEn: "Engine Internal Components", icon: Wrench, description: "Motor iç aksamı ve yapı parçalarında hassas mühendislik gerektiren kategori.", descriptionEn: "Precision-engineered internal engine and structural components.", brandSlugs: ["borgwarner", "contitech", "corteco", "elring", "febi", "gates", "ina", "ioto", "kingpiston", "mahle", "rapro", "supsan", "swag", "taifun", "ucel"], featuredBrandSlugs: ["mahle", "borgwarner", "elring", "ina", "kingpiston", "ioto"] },
  { name: "Motor Yağı", nameEn: "Engine Oil", icon: Droplet, description: "Motor yağı ve yağlama ürünlerinde uluslararası performans standartları.", descriptionEn: "International performance standards in engine oil and lubrication products.", brandSlugs: ["liquimoly", "spart", "swag", "wolflubricants"], featuredBrandSlugs: ["liquimoly", "spart", "wolflubricants", "swag"] },
  { name: "Şanzıman", nameEn: "Transmission", icon: Settings2, description: "Şanzıman ve güç aktarma organlarında OEM eşdeğeri parça kapsamı.", descriptionEn: "OEM-equivalent parts coverage for transmission and power transmission units.", brandSlugs: ["bosch", "febi", "ina", "luk", "skf", "swag", "vitesco"], featuredBrandSlugs: ["luk", "ina", "skf", "bosch", "vitesco"] },
  { name: "Sarf ve Bakım Ürünleri", nameEn: "Consumables & Maintenance Products", icon: PackageCheck, description: "Periyodik bakım ve sarf malzemelerinde tam kapsamlı ürün gamı.", descriptionEn: "A comprehensive product range for scheduled maintenance and consumables.", brandSlugs: ["bosch", "denso", "febi", "ferodo", "henkel", "liquimoly", "spart", "swag", "valeo", "wolflubricants"], featuredBrandSlugs: ["liquimoly", "henkel", "bosch", "spart", "valeo"] },
  { name: "Şarj-Marş", nameEn: "Charging & Starting", icon: BatteryCharging, description: "Marş motoru ve alternatör grubunda güvenilir performans.", descriptionEn: "Reliable performance in starter motors and alternators.", brandSlugs: ["bosch", "cargo", "contitech", "denso", "fag", "gates", "hella", "ina", "segautomotive", "skf", "swag", "valeo"], featuredBrandSlugs: ["bosch", "denso", "valeo", "segautomotive", "hella"] },
  { name: "Soğutma", nameEn: "Cooling", icon: Snowflake, description: "Radyatör ve motor soğutma sisteminde ısı yönetimi çözümleri.", descriptionEn: "Thermal management solutions for radiators and engine cooling systems.", brandSlugs: ["behr", "blueprint", "bosch", "delphi", "denso", "elring", "era", "febi", "gates", "hlmando", "hella", "kale", "mahle", "nrf", "rapro", "sachs", "spart", "swag", "ucel", "valeo"], featuredBrandSlugs: ["behr", "nrf", "mahle", "gates", "valeo", "spart"] },
  { name: "Süspansiyon ve Taşıyıcı Sistem", nameEn: "Suspension & Chassis Support", icon: MoveVertical, description: "Amortisör, salıncak ve taşıyıcı sistem parçalarında sürüş konforu.", descriptionEn: "Driving comfort through shock absorbers, control arms and chassis support components.", brandSlugs: ["blueprint", "corteco", "delphi", "fag", "febi", "ina", "lemforder", "monroe", "rapro", "sachs", "skf", "spart", "swag", "teknorot", "trw", "ucel", "valeo"], featuredBrandSlugs: ["monroe", "sachs", "lemforder", "trw", "teknorot", "spart"] },
  { name: "Üniversal Ürünler", nameEn: "Universal Products", icon: Boxes, description: "Araç bağımsız, geniş uygulama alanına sahip evrensel ürün grubu.", descriptionEn: "A vehicle-independent product group with broad application coverage.", brandSlugs: ["bosch", "cargo", "delphi", "elring", "osram", "skf", "spart"], featuredBrandSlugs: ["bosch", "skf", "osram", "spart", "delphi"] },
  { name: "Yakıt ve Enjeksiyon", nameEn: "Fuel & Injection", icon: Fuel, description: "Yakıt pompası ve enjeksiyon sisteminde hassas performans parçaları.", descriptionEn: "Precision performance parts for fuel pumps and injection systems.", brandSlugs: ["behr", "borgwarner", "bosch", "delphi", "denso", "era", "febi", "hella", "kale", "mahle", "ngk", "spart", "valeo", "vdo"], featuredBrandSlugs: ["bosch", "delphi", "denso", "vdo", "spart"] },
];
