// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/delta-oto/HakkimizdaPage.tsx": () => import("../components/mockups/delta-oto/HakkimizdaPage.tsx"),
  "./components/mockups/delta-oto/IletisimPage.tsx": () => import("../components/mockups/delta-oto/IletisimPage.tsx"),
  "./components/mockups/delta-oto/KariyerPage.tsx": () => import("../components/mockups/delta-oto/KariyerPage.tsx"),
  "./components/mockups/delta-oto/LandingPage.tsx": () => import("../components/mockups/delta-oto/LandingPage.tsx"),
  "./components/mockups/delta-oto/OperasyonPage.tsx": () => import("../components/mockups/delta-oto/OperasyonPage.tsx"),
  "./components/mockups/delta-oto/TedarikciPage.tsx": () => import("../components/mockups/delta-oto/TedarikciPage.tsx")
};
